(function() {
  var dict = {
      "Unknown": "Inconnu",
      "And": "ET",
      "Authenticating": "Authentification à {0} en cours...",
      "Clear": "Effacer {0}",
      "CompleteQuery": "Requête complète",
      "Exclude": "Exclure {0}",
      "EnterTag": "Ajouter un Tag",
      "Next": "Suivant",
      "Last": "Précédent",
      "Link": "Lien",
      "Or": "OU",
      "Previous": "Précédent",
      "QueryDidntMatchAnyDocuments": "Votre requête n'a retourné aucun document.",
      "QueryException": "Votre requête a un erreur: {0}.",
      "Me": "Moi",
      "Remove": "Enlever",
      "Search": "Recherche",
      "SearchFor": "Recherche pour {0}",
      "ShareQuery": "Partager cette requête",
      "Preferences": "Préférences",
      "LinkOpeningSettings": "Réglage pour l'ouverture des liens",
      "Reauthenticate": "Réauthentifier {0}",
      "ResultsFilteringExpression": "Expression de filtrage des résultats",
      "FiltersInYourPreferences": "Filtres dans vos préférences",
      "Create": "Créer",
      "SearchIn": "Rechercher dans {0}",
      "Seconds": "en {0} seconde<pl>s</pl>",
      "ShowingResultsOf": "Résultat<pl>s</pl> {0}<pl>-{1}</pl> de {2}",
      "SwitchTo": "Basculer vers {0}",
      "Unexclude": "Réinclure {0}",
      "ClearAllFilters": "Enlever tous les filtres",
      "SkipLogin": "Passer la connexion",
      "LoginInProgress": "Connexion en cours, veuillez patienter ...",
      "Login": "Connexion",
      "GetStarted": "Démarrer",
      "More": "Plus",
      "Less": "Moins",
      "Settings": "Réglages",
      "Score": "Score",
      "ScoreDescription": "Le score est calculé en fonction du nombre d'occurences et de sa position dans les résultats",
      "Occurrences": "Occurrences",
      "OccurrencesDescription": "Trier selon l'occurence, avec les valeurs les plus hautes apparaissant en premier.",
      "Label": "Étiquette",
      "Of": "de",
      "LabelDescription": "Trier alphabétiquement sur la valeur des champs",
      "Value": "Valeur",
      "ValueDescription": "Trier sur les valeurs du premier champ calculé",
      "AlphaAscending": "Valeur croissante",
      "AlphaDescending": "Valeur Décroissante",
      "ChiSquare": "Chi Square",
      "Nosort": "Aucun tri",
      "RelativeFrequency": "Fréquence Relative",
      "RelativeFrequencyDescription": "Trier sur la fréquence relative des valeurs. Les valeurs moins fréquentes vont apparaîtrent plus haute.",
      "Custom": "Personnalisé",
      "CustomDescription": "Trier de manière personalisée",
      "ComputedField": "Champ calculé",
      "Ascending": "croissant",
      "Descending": "décroissant",
      "noResultFor": "Pas de résultats pour {0}",
      "autoCorrectedQueryTo": "Requête a été corrigée automatiquement à {0}",
      "didYouMean": "Vouliez-vous dire: {0}",
      "SuggestedResults": "Résultats Suggérés",
      "SuggestedQueries": "Requêtes Suggérées",
      "MostRelevantItems": "Items les plus pertinents :",
      "AllItems": "Tous les items :",
      "ShowLess": "Voir moins de résultats",
      "ShowMore": "Voir plus de résultats",
      "HideFacet": "Cacher la Facette",
      "ShowFacet": "Afficher la Facette",
      "AndOthers": "et {0} autre<pl>s</pl>",
      "MostRelevantPosts": "Messages les plus pertinents :",
      "CompleteThread": "Toute la discussion :",
      "ShowCompleteThread": "Voir l'ensemble de la discussion",
      "ShowOnlyTopMatchingPosts": "Voir seulement les messages pertinents",
      "MostRelevantReplies": "Réponses les plus pertinentes :",
      "AllConversation": "Toute la conversation :",
      "ShowAllConversation": "Voir l'ensemble de la conversation",
      "ShowAllReplies": "Voir toutes les réponses",
      "ShowOnlyMostRelevantReplies": "Voir seulement les réponses les plus pertinentes",
      "Close": "Fermer",
      "Open": "Ouvrir",
      "OpenInOutlookWhenPossible": "Ouvrir dans Outlook (quand c'est possible)",
      "AlwaysOpenInNewWindow": "Toujours ouvrir les résultats dans une nouvelle fenêtre",
      "QuickView": "Coup D'Oeil ",
      "ErrorReport": "Rapport D'Erreur",
      "OopsError": "Oops! Une erreur côté serveur s'est produite.",
      "ProblemPersists": "Si le problème persiste, contactez l'administrateur.",
      "GoBack": "Retour en arrière",
      "Reset": "Réinitialiser",
      "Retry": "Réessayer",
      "MoreInfo": "Plus d'information",
      "Username": "Nom d'utilisateur",
      "Password": "Mot de passe",
      "CannotConnect": "Impossible de se connecter au serveur.",
      "BadUserPass": "Mauvaise combinaison de nom d'utilisateur et mot de passe.",
      "PleaseEnterYourCredentials": "Veuillez entrer votre nom d'utilisateur et mot de passe pour {0}.",
      "PleaseEnterYourSearchPage": "Veuillez entrer votre URL de page de recherche",
      "Collapse": "Fermer",
      "Expand": "Réduire",
      "Today": "Aujourd'hui",
      "Yesterday": "Hier",
      "Tomorrow": "Demain",
      "Duration": "Durée: {0}",
      "IndexDuration": "Durée Index: {0}",
      "ProxyDuration": "Durée Proxy: {0}",
      "ClientDuration": "Durée Client: {0}",
      "Unavailable": "Non disponible",
      "Reply": "Répondre",
      "ReplyAll": "Répondre à tous",
      "Forward": "Transférer",
      "From": "De",
      "Caption": "Légende",
      "Expression": "Expression",
      "Tab": "Onglet",
      "Tabs": "Onglets",
      "EnterExpressionName": "Entrez Nom d'Expression",
      "EnterExpressionToFilterWith": "Entrez l'Expression Pour Filtrer Vos Résultats",
      "SelectTab": "Selectionnez Onglet",
      "SelectAll": "Sélectionnez Tout",
      "PageUrl": "URL de la page de recherche",
      "ErrorSavingToDevice": "Erreur lors de l'écriture sur votre appareil",
      "ErrorReadingFromDevice": "Erreur lors de la lecture de l'information sur votre appareil",
      "AppIntro": "Contactez-nous pour parler avec un spécialiste de produit qui pourra répondre à vos questions a propos de Coveo. Ou bien, essayer une demonstration !",
      "TryDemo": "Essayer le demo",
      "ContactUs": "Contactez-nous",
      "NewToCoveo": "Qu'est-ce que Coveo ?",
      "LetUsHelpGetStarted": "Laisser nous vous aidez a démarrer",
      "CannotConnectSearchPage": "Impossible de rejoindre votre page de recherche",
      "AreYouSureDeleteFilter": "Êtes vous sur de vouloir effacer le filtre {0} avec l'expression {1}",
      "OnlineHelp": "Aide en Ligne",
      "Done": "Terminé",
      "SaveFacetState": "Sauvegarder l'état de la facette",
      "ClearFacetState": "Effacer l'état de la facette",
      "DisplayingTheOnlyMessage": "Affichage du seul message dans cette conversation",
      "NoNetworkConnection": "Aucune connexion réseau",
      "UnknownConnection": "Connexion inconnue",
      "EthernetConnection": "Connexion ethernet",
      "WiFi": "Connexion WiFi",
      "CELL": "Connexion cellulaire",
      "CELL_2G": "Connexion cellulaire 2g",
      "CELL_3G": "Connexion cellulaire 3g",
      "CELL_4G": "Connexion cellulaire 4g",
      "QueryExceptionNoException": "Aucune exception",
      "QueryExceptionInvalidSyntax": "Syntaxe invalide",
      "QueryExceptionInvalidCustomField": "Champ personnalisé invalide",
      "QueryExceptionInvalidDate": "Date invalide",
      "QueryExceptionInvalidExactPhrase": "Phrase exacte invalide",
      "QueryExceptionInvalidDateOp": "Opérateur de date non valide",
      "QueryExceptionInvalidNear": "Fonction de proximité invalide",
      "QueryExceptionInvalidWeightedNear": "Pondérée de la fonction de proximité invalide",
      "QueryExceptionInvalidTerm": "Terme invalide",
      "QueryExceptionTooManyTerms": "Trop de termes",
      "QueryExceptionWildcardTooGeneral": "Métacaractère trop général",
      "QueryExceptionInvalidSortField": "Champ de tri non valide",
      "QueryExceptionInvalidSmallStringOp": "Petit opérateur de chaîne non valide",
      "QueryExceptionRequestedResultsMax": "Demandé maximal de résultats",
      "QueryExceptionAggregatedMirrorDead": "Miroir agrégé est hors-ligne",
      "QueryExceptionAggregatedMirrorQueryTimeOut": "Délai de requête du miroir agrégé dépassé",
      "QueryExceptionAggregatedMirrorInvalidBuildNumber": "Numéro de version du miroir agrégées invalide",
      "QueryExceptionAggregatedMirrorCannotConnect": "Connection impossible au miroir agrégées",
      "QueryExceptionNotEnoughLeadingCharsWildcard": "Pas assez de charateur princial pour le métacaractère",
      "QueryExceptionSecurityInverterNotFound": "Inverseur de sécurité introuvable",
      "QueryExceptionSecurityInverterAccessDenied": "Accès refusé à l'inverseur de sécurité ",
      "QueryExceptionAggregatedMirrorCannotImpersonate": "Miroir agrégées ne peut pas usurper l'identité",
      "QueryExceptionUnexpected": "Inattendu",
      "QueryExceptionAccessDenied": "Accès refusé",
      "QueryExceptionSuperUserTokenInvalid": "Jeton du super-utilisateur invalide",
      "QueryExceptionSuperUserTokenExpired": "Jeton du super-utilisateur est expiré",
      "QueryExceptionLicenseQueriesExpired": "licence de requêtes est expirée",
      "QueryExceptionLicenseSuperUserTokenNotSupported": "licence de jeton de super utilisateur non pris en charge",
      "QueryExceptionInvalidSession": "Session incorrecte",
      "QueryExceptionInvalidDocument": "Document non valide",
      "QueryExceptionSearchDisabled": "Recherche désactivée",
      "objecttype_people": "Personne",
      "objecttype_message": "Message",
      "objecttype_feed": "Flux RSS",
      "objecttype_thread": "Fil de conversation",
      "objecttype_board": "",
      "objecttype_category": "",
      "objecttype_account": "Compte",
      "objecttype_campaign": "Campagne",
      "objecttype_case": "Cas",
      "objecttype_contact": "Contact",
      "objecttype_contract": "Contrat",
      "objecttype_event": "Évènement",
      "objecttype_lead": "Piste",
      "objecttype_solution": "Solution",
      "objecttype_task": "Tâche",
      "objecttype_user": "Utilisateur",
      "objecttype_attachment": "Attachement",
      "objecttype_casecomment": "Commentaire sur un cas",
      "objecttype_opportunity": "Opportunité",
      "objecttype_note": "Note",
      "objecttype_product": "Produit",
      "objecttype_partner": "Partenaire",
      "objecttype_kbdocumentation": "Documentation",
      "objecttype_kbsolution": "Solution",
      "objecttype_kbknowledgearticle": "Article de base de connaissance",
      "objecttype_kbattachment": "Attachement",
      "sysfiletype_html": "Fichier HTML",
      "sysfiletype_image": "Image",
      "sysfiletype_folder": "Dossier",
      "sysfiletype_txt": "Texte",
      "sysfiletype_zip": "Fichier compressé",
      "sysfiletype_pdf": "Fichier PDF",
      "sysfiletype_xml": "Fichier XML",
      "sysfiletype_doc": "Document Word",
      "sysfiletype_xls": "Document Excel",
      "sysfiletype_ppt": "Document PowerPoint",
      "sysfiletype_video": "Vidéo",
      "sysfiletype_exchangemessage": "Message",
      "sysfiletype_exchangeappointment": "Rendez-vous",
      "sysfiletype_exchangenote": "Note",
      "sysfiletype_exchangetask": "Tâche",
      "sysfiletype_exchangeperson": "Utilisateur exchange",
      "sysfiletype_activedirperson": "Utilisateur active directory",
      "sysfiletype_exchangeactivity": "Activité",
      "sysfiletype_exchangecalendarmessage": "Message calendrier",
      "sysfiletype_exchangedocument": "Document exchange",
      "sysfiletype_exchangerssfeed": "Flux RSS",
      "sysfiletype_exchangejunkmessage": "Courrier indésirable",
      "sysfiletype_exchangeofficecom": "Communications",
      "sysfiletype_spportal": "Portail",
      "sysfiletype_spsite": "Site",
      "sysfiletype_spuserprofile": "Utilisateur SharePoint",
      "sysfiletype_sparea": "Zone",
      "sysfiletype_spannouncement": "Annonce",
      "sysfiletype_spannouncementlist": "Annonces",
      "sysfiletype_spcontact": "Contact",
      "sysfiletype_spcontactlist": "Contacts",
      "sysfiletype_spcustomlist": "Listes personnalisées",
      "sysfiletype_spdiscussionboard": "Babillard de discussion",
      "sysfiletype_spdiscussionboardlist": "Babillards de discussion",
      "sysfiletype_spdocumentlibrarylist": "Bibliothèque de documents",
      "sysfiletype_spevent": "Événement",
      "sysfiletype_speventlist": "Événements",
      "sysfiletype_spformlibrarylist": "Bibliothèque de formulaires",
      "sysfiletype_spissue": "Problème",
      "sysfiletype_spissuelist": "Problèmes",
      "sysfiletype_splink": "Lien",
      "sysfiletype_splinklist": "Liens",
      "sysfiletype_sppicturelibrarylist": "Bibliothèque d'images",
      "sysfiletype_spsurvey": "Sondage",
      "sysfiletype_spsurveylist": "Sondages",
      "sysfiletype_sptask": "Tâche",
      "sysfiletype_sptasklist": "Tâches",
      "sysfiletype_spagenda": "Agenda",
      "sysfiletype_spagendalist": "Agendas",
      "sysfiletype_spattendee": "Participant",
      "sysfiletype_spattendeelist": "Participants",
      "sysfiletype_spcustomgridlist": "Grilles personnalisées",
      "sysfiletype_spdecision": "Décision",
      "sysfiletype_spdecisionlist": "Décisions",
      "sysfiletype_spobjective": "Objectif",
      "sysfiletype_spobjectivelist": "Objectifs",
      "sysfiletype_sptextbox": "Zone de texte",
      "sysfiletype_sptextboxlist": "Zones de texte",
      "sysfiletype_spthingstobring": "Élément à prévoir",
      "sysfiletype_spthingstobringlist": "Éléments à prévoir",
      "sysfiletype_sparealisting": "Liste de zones",
      "sysfiletype_spmeetingserie": "Espace de travail de réunion",
      "sysfiletype_spmeetingserielist": "Liste d'espace de travail de réunion",
      "sysfiletype_spsitedirectory": "Élément d'un répertoire de sites",
      "sysfiletype_spsitedirectorylist": "Répertoire des sites",
      "sysfiletype_spdatasource": "Source de données",
      "sysfiletype_spdatasourcelist": "Liste de sources de données",
      "sysfiletype_splisttemplatecataloglist": "Catalogue de modèles de listes",
      "sysfiletype_spwebpartcataloglist": "Catalogue de composants WebPart",
      "sysfiletype_spwebtemplatecataloglist": "Catalogue de modèles de pages Web",
      "sysfiletype_spworkspacepagelist": "Liste de pages d'espace de travail",
      "sysfiletype_spunknownlist": "Liste personnalisée",
      "sysfiletype_spadministratortask": "Tâche d'administrateur",
      "sysfiletype_spadministratortasklist": "Tâches d'administrateur",
      "sysfiletype_spareadocumentlibrarylist": "Bibliothèque de documents zonés",
      "sysfiletype_spblogcategory": "Catégorie de blogue",
      "sysfiletype_spblogcategorylist": "Catégorie de blogue",
      "sysfiletype_spblogcomment": "Commentaire de blogue",
      "sysfiletype_spblogcommentlist": "Commentaires de blogue",
      "sysfiletype_spblogpost": "Article de blogue",
      "sysfiletype_spblogpostlist": "Articles de blogue",
      "sysfiletype_spdataconnectionlibrarylist": "Bibliothèque de connexions",
      "sysfiletype_spdistributiongroup": "Groupe de distribution",
      "sysfiletype_spdistributiongrouplist": "Groupes de distribution",
      "sysfiletype_spipfslist": "Serveurs de formulaire InfoPath",
      "sysfiletype_spkeyperformanceindicator": "Indicateur de performance clé",
      "sysfiletype_spkeyperformanceindicatorlist": "Indicateurs de performance clé",
      "sysfiletype_splanguagesandtranslator": "Langue et traducteur",
      "sysfiletype_splanguagesandtranslatorlist": "Langues et traducteurs",
      "sysfiletype_spmasterpagescataloglist": "Bibliothèque de pages maîtres",
      "sysfiletype_spnocodeworkflowlibrarylist": "Bibliothèque de séquences non codées",
      "sysfiletype_spprojecttask": "Tâche de projet",
      "sysfiletype_spprojecttasklist": "Tâches de projet",
      "sysfiletype_sppublishingpageslibrarylist": "Bibliothèque de page",
      "sysfiletype_spreportdocumentlibrarylist": "Bibliothèque de documents rapport",
      "sysfiletype_spreportlibrarylist": "Bibliothèque de rapports",
      "sysfiletype_spslidelibrarylist": "Bibliothèque de diapositives",
      "sysfiletype_sptab": "Onglets",
      "sysfiletype_sptablist": "Liste d'onglets",
      "sysfiletype_sptranslationmanagementlibrarylist": "Bibliothèque de traductions",
      "sysfiletype_spuserinformation": "Information d'utilisateur",
      "sysfiletype_spuserinformationlist": "Liste d'information d'utilisateur",
      "sysfiletype_spwikipagelibrarylist": "Bibliothèque de pages Wiki",
      "sysfiletype_spworkflowhistory": "Historique de processus",
      "sysfiletype_spworkflowhistorylist": "Historiques de processus",
      "sysfiletype_spworkflowprocess": "Séquence de tâche personnalisée",
      "sysfiletype_spworkflowprocesslist": "Séquence de tâches personnalisées",
      "sysfiletype_sppublishingimageslibrarylist": "Bibliothèque d'images de publication",
      "sysfiletype_spcirculation": "Circulation",
      "sysfiletype_spcirculationlist": "Circulations",
      "sysfiletype_spdashboardslibrarylist": "Bibliothèque de tableaux de bord",
      "sysfiletype_spdataconnectionforperformancepointlibrarylist": "Bibliothèque de connexions pour la performance",
      "sysfiletype_sphealthreport": "Rapport de santé",
      "sysfiletype_sphealthreportlist": "Rapports de santé",
      "sysfiletype_sphealthrule": "Règle de santé",
      "sysfiletype_sphealthrulelist": "Règles de santé",
      "sysfiletype_spimedictionary": "Dictionnaire IME",
      "sysfiletype_spimedictionarylist": "Dictionnaires IME",
      "sysfiletype_spperformancepointcontent": "Contenu de point de performance",
      "sysfiletype_spperformancepointcontentlist": "Contenus de point de performance",
      "sysfiletype_spphonecallmemo": "Mémo d'appel téléphonique",
      "sysfiletype_spphonecallmemolist": "Mémos d'appel téléphonique",
      "sysfiletype_sprecordlibrarylist": "Bibliothèque d'enregistrements",
      "sysfiletype_spresource": "Ressource",
      "sysfiletype_spresourcelist": "Ressources",
      "sysfiletype_spprocessdiagramslibrarylist": "Bibliothèque de diagrammes de processus",
      "sysfiletype_spsitethemeslibrarylist": "Bibliothèque de thèmes de site",
      "sysfiletype_spsolutionslibrarylist": "Bibliothèque de solutions",
      "sysfiletype_spwfpublibrarylist": "Bibliothèque de WFPUB",
      "sysfiletype_spwhereabout": "Endroit",
      "sysfiletype_spwhereaboutlist": "Endroits",
      "sysfiletype_spdocumentlink": "Lien vers un document",
      "sysfiletype_spdocumentset": "Ensemble de documents",
      "sysfiletype_spmicrofeedpost": "Billet d'un microfil de nouvelles",
      "sysfiletype_spmicrofeedlist": "Microfil de nouvelles",
      "sysfiletype_splistfolder": "Dossier de liste",
  }
  var locales = String["locales"] || (String["locales"] = {});
  locales["fr"] = dict;
  String["toLocaleString"].call(this, { "fr": dict });
  String["locale"] = "fr";
  String["defaultLocale"] = "en";
})();
/*
 * Globalize Culture fr-FR
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "fr-FR", "default", {
	name: "fr-FR",
	englishName: "French (France)",
	nativeName: "français (France)",
	language: "fr",
	numberFormat: {
		",": " ",
		".": ",",
		"NaN": "Non Numérique",
		negativeInfinity: "-Infini",
		positiveInfinity: "+Infini",
		percent: {
			",": " ",
			".": ","
		},
		currency: {
			pattern: ["-n $","n $"],
			",": " ",
			".": ",",
			symbol: "€"
		}
	},
	calendars: {
		standard: {
			firstDay: 1,
			days: {
				names: ["dimanche","lundi","mardi","mercredi","jeudi","vendredi","samedi"],
				namesAbbr: ["dim.","lun.","mar.","mer.","jeu.","ven.","sam."],
				namesShort: ["di","lu","ma","me","je","ve","sa"]
			},
			months: {
				names: ["janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre",""],
				namesAbbr: ["janv.","févr.","mars","avr.","mai","juin","juil.","août","sept.","oct.","nov.","déc.",""]
			},
			AM: null,
			PM: null,
			eras: [{"name":"ap. J.-C.","start":null,"offset":0}],
			patterns: {
				d: "dd/MM/yyyy",
				D: "dddd d MMMM yyyy",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "dddd d MMMM yyyy HH:mm",
				F: "dddd d MMMM yyyy HH:mm:ss",
				M: "d MMMM",
				Y: "MMMM yyyy"
			}
		}
	}
});

}( this ));
